version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: app_front-nextjs
    volumes:
      - .:/usr/src/app/app_front
    env_file:
      - .env 
    command: npm run dev